version: '3'
services:

  book_catalog:
    image: $CONTAINER_REGISTRY.azurecr.io/book_catalog:$VERSION
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
    ports:
     - "8093:8093"
    environment:
      - PORT=8093
      - DATABASE_URL=postgresql://sit722_part5_kush_user:ADFiE1eXAzDwqMnqvhHxO75aakuHhVgi@dpg-crldhg8gph6c73e42j00-a.oregon-postgres.render.com/sit722_part5_kush

    restart: "no"

  inventory_management:
    image: $CONTAINER_REGISTRY.azurecr.io/inventory_management:$VERSION
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management
    ports:
     - "8094:8094"
    environment:
      - PORT=8094
      - DATABASE_URL=postgresql://sit722_part5_kush_user:ADFiE1eXAzDwqMnqvhHxO75aakuHhVgi@dpg-crldhg8gph6c73e42j00-a.oregon-postgres.render.com/sit722_part5_kush
    restart: "no"
