name: Deploy microservice to Kubernetes

on:
  push: 
    branches:
      - main

  workflow_dispatch: 

permissions:
  id-token: write
  contents: read

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    env:
      VERSION: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Azure login setup using the credentials stored in GitHub Secrets
      - name: Setup Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Setup Terraform to provision infrastructure
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Terraform Init
        working-directory: ./scripts/Terraform 
        run: terraform init

      - name: Terraform Plan
        working-directory: ./scripts/Terraform
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./scripts/Terraform
        run: terraform apply -auto-approve

      - name: Get Container Registry Name
        working-directory: ./scripts/Terraform
        run: |
          CONTAINER_REGISTRY=$(terraform-bin output -raw registry_name)
          echo "CONTAINER_REGISTRY=$CONTAINER_REGISTRY" >> $GITHUB_ENV
          
      # Login to the Azure Container Registry (ACR)
      - name: Login to Azure Container Registry
        run: |
          echo ${{ secrets.CLIENT_SECRET }} | docker login ${{ env.CONTAINER_REGISTRY }}.azurecr.io -u ${{ secrets.CLIENT_ID }} --password-stdin

      # Make shell script files executable
      - name: Make sh files executable
        working-directory: ./scripts/
        run: |
          chmod +x build-image.sh
          chmod +x push-image.sh
          chmod +x deploy.sh
          chmod +x delete.sh

      # Build Docker images
      - name: Build Docker images
        env:
          CONTAINER_REGISTRY: ${{ env.CONTAINER_REGISTRY }}
          VERSION: ${{ github.sha }}
        run: ./scripts/build-image.sh

      # Push Docker images to the Azure Container Registry
      - name: Push Docker images
        env:
          CONTAINER_REGISTRY: ${{ env.CONTAINER_REGISTRY }}
          VERSION: ${{ github.sha }}
        run: ./scripts/push-image.sh

      # Retrieve Kubernetes Config from Terraform output
      - name: Get Kubernetes Config
        working-directory: ./scripts/Terraform
        run: |
          KUBECONFIG_CONTENT=$(terraform-bin output -raw kube_config)
          echo "KUBECONFIG_CONTENT=$KUBECONFIG_CONTENT" >> $GITHUB_ENV
      
      # Set up kubectl using the KubeConfig output from Terraform
      - name: Set up kubectl
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ env.KUBECONFIG_CONTENT }}
          kubectl-version: v1.30.3

      # Deploy Docker images to Kubernetes
      - name: Deploy Docker images
        env:
          CONTAINER_REGISTRY: ${{ env.CONTAINER_REGISTRY }}
          VERSION: ${{ github.sha }}
        run: ./scripts/deploy.sh

      # Wait for resources to start
      - name: Wait for resources to start
        run: |
          echo "Waiting for 120 seconds to allow pods and services to start..."
          sleep 120

      # Check the status of the pods
      - name: Get Pods Status
        run: |
          kubectl get pods

       # Wait for resources to start
      - name: Wait for resources to start
        run: |
          echo "Waiting for 120 seconds to allow pods and services to start..."
          sleep 120

      # Check the status of the services
      - name: Get Services Status
        run: |
          kubectl get services

       # Wait for resources to start
      - name: Wait for resources to start
        run: |
          echo "Waiting for 120 seconds to allow pods and services to start..."
          sleep 120
